/* CRIANDO UMA BASE DE DADOS PARA A OFICINA CAR+ */
CREATE DATABASE OFICINA;

/*USANDO O BD*/
USE OFICINA;

/*CRIANDO A TABELA DE ENDEREÇO*/
CREATE TABLE ENDEREÇO(
	IDENDEREÇO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    NUMERO INT NOT NULL,
    CEP VARCHAR(30) NOT NULL
);
/*CRIANDO A TABELA DE PESSOA*/
CREATE TABLE PESSOA(
	IDPESSOA INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
    CPF VARCHAR(30) UNIQUE NOT NULL,
	SEXO ENUM('M','F'),
    TELEFONE VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(30),
    TIPO ENUM('C', 'F'),  /* C - CLIENTE | F - FUNCIONARIO*/
	IDENDEREÇO INT
);
/*ADICIONANDO A FOREGN KEY NA TABELA ENDEREÇO*/
ALTER TABLE PESSOA
ADD CONSTRAINT FK_PESSOA_ENDEREÇO
FOREIGN KEY(IDENDEREÇO)
REFERENCES ENDEREÇO(IDENDEREÇO);

/*CRIANDO A TABELA DE CLIENTES*/
CREATE TABLE CLIENTES(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    CPF VARCHAR(30) NOT NULL,
    TELEFONE VARCHAR(30) NOT NULL,
    IDPESSOA INT
    );

/*ADICIONANDO A FOREGN KEY NA TABELA CLIENTE*/    
ALTER TABLE CLIENTES
ADD CONSTRAINT FK_CLIENTE_PESSOA
FOREIGN KEY(IDPESSOA)
REFERENCES PESSOA(IDPESSOA);

/*CRIANDO A TABELA DE FUNCIONARIOS*/
CREATE TABLE FUNCIONARIOS(
	IDFUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    CPF VARCHAR(30) NOT NULL,
    TELEFONE VARCHAR(30) NOT NULL,
    SALARIO DECIMAL(10,2),
    CARGO VARCHAR(30),
    IDPESSOA INT
    );

/*ADICIONANDO A FOREGN KEY NA TABELA FUNCIONARIOS*/
ALTER TABLE FUNCIONARIOS
ADD CONSTRAINT FK_FUNCIONARIO_PESSOA
FOREIGN KEY(IDPESSOA)
REFERENCES PESSOA(IDPESSOA);

/*CRIANDO UMA TRIGGER PARA ADICIONAR AUTOMATICAMENTE OS DADOS DA TABELA PESSOA NA TABELA CLIENTE DE ACORDO COM O TIPO.*/
DELIMITER $
CREATE TRIGGER addCLIENTES
AFTER INSERT ON PESSOA
FOR EACH ROW
BEGIN
		INSERT INTO CLIENTES(NOME, CPF, TELEFONE, IDPESSOA)
		SELECT NOME, CPF, TELEFONE, IDPESSOA FROM PESSOA
		WHERE IDPESSOA NOT IN (SELECT IDPESSOA FROM CLIENTES) AND TIPO = 'C';
END $
DELIMITER ;

/*CRIANDO UMA TRIGGER PARA ADICIONAR AUTOMATICAMENTE OS DADOS DA TABELA PESSOA NA TABELA FUNCIONARIO DE ACORDO COM O TIPO.*/
DELIMITER $
CREATE TRIGGER addFUNCIONARIOS
AFTER INSERT ON PESSOA
FOR EACH ROW
BEGIN
		INSERT INTO FUNCIONARIOS(NOME, CPF, TELEFONE, IDPESSOA)
		SELECT NOME, CPF, TELEFONE, IDPESSOA FROM PESSOA
		WHERE IDPESSOA NOT IN (SELECT IDPESSOA FROM FUNCIONARIOS) AND TIPO = 'F';
        
END $
DELIMITER ;

/*CRIANDO A TABELA DE CARROS*/
CREATE TABLE CARROS(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(30) NOT NULL,
	PLACA VARCHAR(30) NOT NULL UNIQUE,
	IDMARCA INT,
    IDCLIENTE INT
);

/*CRIANDO A TABELA DE MARCA DOS CARROS*/
CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) UNIQUE
);

/*ADICIONANDO A FOREGN KEY NA TABELA CARROS*/
ALTER TABLE CARROS
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(IDMARCA)
REFERENCES MARCA(IDMARCA);

ALTER TABLE CARROS
ADD CONSTRAINT FK_CARRO_PROPRIETARIO
FOREIGN KEY(IDCLIENTE)
REFERENCES CLIENTES(IDCLIENTE);

/*CRIANDO A TABELA DE SERVIÇOS*/
CREATE TABLE SERVIÇOS(
	IDSERVIÇO INT PRIMARY KEY AUTO_INCREMENT,
	PREÇO_T DECIMAL(10,2),
    IDPINTURA INT,
    IDMANUTENÇÃO INT,
    IDFUNCIONARIO INT
);

/*CRIANDO A TABELA DE PINTURA*/
CREATE TABLE PINTURA(
	IDPINTURA INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(30),
	TIPO VARCHAR(30),
	PREÇO_P DECIMAL(10,2)
);

/*CRIANDO A TABELA DE MANUTENÇÃO*/
CREATE TABLE MANUTENÇÃO(
	IDMANUTENÇÃO INT PRIMARY KEY AUTO_INCREMENT,
	TIPO VARCHAR(30),
	PREÇO_M DECIMAL(10,2)
);

/*ADICIONANDO A FOREGN KEY NA TABELA SERVIÇOS*/
ALTER TABLE SERVIÇOS
ADD CONSTRAINT FK_SERVIÇO_FUNCIONARIO
FOREIGN KEY(IDFUNCIONARIO)
REFERENCES FUNCIONARIOS(IDFUNCIONARIO);

ALTER TABLE SERVIÇOS
ADD CONSTRAINT FK_SERVIÇOS_PINTURA
FOREIGN KEY(IDPINTURA)
REFERENCES PINTURA(IDPINTURA);

ALTER TABLE SERVIÇOS
ADD CONSTRAINT FK_SERVIÇOS_MANUTENÇÃO
FOREIGN KEY(IDMANUTENÇÃO)
REFERENCES MANUTENÇÃO(IDMANUTENÇÃO);

/*CRIANDO A TABELA DE CONTRATO*/
CREATE TABLE CONTRATO(
	IDSERVIÇO INT ,
	IDCARRO INT,
    PRIMARY KEY(IDSERVIÇO,IDCARRO)
);

/*ADICIONANDO A FOREGN KEY NA TABELA CONTRATO*/
ALTER TABLE CONTRATO
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(IDCARRO)
REFERENCES CARROS(IDCARRO);

ALTER TABLE CONTRATO
ADD CONSTRAINT FK_SERVIÇO
FOREIGN KEY(IDSERVIÇO)
REFERENCES SERVIÇOS(IDSERVIÇO);
/*--------------------------------------------------------------------------------------------------------------*/

/*INSERINDO ENDEREÇOS*/

INSERT INTO ENDEREÇO VALUES(NULL, 'Rua Paraná', 'São Sebastião', 350 , '36202-316'); 
INSERT INTO ENDEREÇO VALUES(NULL, 'Rua José Joaquim dos Santos', 'Copacabana', 108 , '31540-524');
INSERT INTO ENDEREÇO VALUES(NULL, 'Rua Cruzador Bahia', 'Dom Bosco', 32 , '36025-430'); 
INSERT INTO ENDEREÇO VALUES(NULL, 'Rua Paulo Ribeiro Bastos', 'Jardim Atlântico', 746 , '31710-430'); 
INSERT INTO ENDEREÇO VALUES(NULL, 'Rua Agostinho Martins Pereira', 'Guanabara', 1020 , '32667-004'); 
INSERT INTO ENDEREÇO VALUES(NULL, 'Avenida A', 'Laranjal', 98 , '36505-338'); 
INSERT INTO ENDEREÇO VALUES(NULL, 'Rua Araraquara', 'Nova Suíssa', 478 , '30421-257'); 
INSERT INTO ENDEREÇO VALUES(NULL, 'Rua Nilse Alves da Silva', 'Dom Silvério', 2483 , '31985-390'); 
INSERT INTO ENDEREÇO VALUES(NULL, 'Avenida Marilene Baduy Goulart', 'Gerson Baduy I', 1785 , '38305-496'); 
INSERT INTO ENDEREÇO VALUES(NULL, 'Praça Nove de Julho', 'Santo Antônio', 273 , '38700-548'); 
INSERT INTO ENDEREÇO VALUES(NULL, 'Rua Calafate', 'Parque das Américas', 857 , '38045-480'); 
INSERT INTO ENDEREÇO VALUES(NULL, 'Rua Doutor José Assis Ribeiro', 'Bom Pastor', 697 , '37014-380'); 

/*INSERINDO PESSOA *COMO TEMOS DUAS TRIGGERS, ASSIM QUE ADICIONA EM PESSOA, CADASTRA AUTOMATICO EM CLIENTE E FUNCIONARIO DE ACORDO COM SEU TIPO*/

INSERT INTO PESSOA VALUES(NULL, 'Anderson Salles Rezende', '338.244.466-69', 'M', '(32) 97438-4865', 'anderson.rezende@gmail.com', 'C', 3);
INSERT INTO PESSOA VALUES(NULL, 'Luiz Carlos Peixoto Guedes', '153.647.946-28', 'M', '(31) 99174-8228', 'luiz.guedes@gmail.com', 'F', 8);
INSERT INTO PESSOA VALUES(NULL, 'Gabrielle Fernandes Vogas', '283.164.656-12', 'F', '(32) 98806-4366', 'gabrielle.vogas@gmail.com', 'C', 12);
INSERT INTO PESSOA VALUES(NULL, 'Anna Pena Teixeira', '565.468.116-85', 'F', '(34) 96939-7330', 'anna.teixeira@gmail.com', 'C', 2);
INSERT INTO PESSOA VALUES(NULL, 'Cláudio Matta Passos', '422.067.136-67', 'M', '(38) 97318-1873', 'claudio.passos@gmail.com', 'F', 6);
INSERT INTO PESSOA VALUES(NULL, 'Josildo Elias de Rodrigues', '924.238.466-65', 'M', '(34) 99677-6545', 'josildo.rodrigues@gmail.com', 'F', 4);
INSERT INTO PESSOA VALUES(NULL, 'Breno Camelo Bento', '720.477.556-20', 'M', '(34) 99525-8737', 'breno.bento@gmail.com', 'C', 5);
INSERT INTO PESSOA VALUES(NULL, 'Lorenna Linhares Rodrigues', '411.125.526-42', 'F', '(33) 98773-2425', 'lorenna.rodrigues@gmail.com', 'C', 7);
INSERT INTO PESSOA VALUES(NULL, 'Guilherme Teixeira Gomes', '543.117.336-74', 'M', '(37) 98014-9988', 'guilherme.gomes@gmail.com', 'C', 9);
INSERT INTO PESSOA VALUES(NULL, 'Vicente Vargas Saldanha', '391.445.226-90', 'M', '(38) 97116-4782', 'vicente.saldanha@gmail.com', 'F', 10);
INSERT INTO PESSOA VALUES(NULL, 'João Marcos Barellos Rangel', '671.166.576-73', 'M', '(34) 98285-1563', 'joao.rangel@gmail.com', 'C', 11);
INSERT INTO PESSOA VALUES(NULL, 'José Maria Diniz Correia', '725.214.216-77', 'M', '(32) 99740-6165', 'jose.correia@gmail', 'C', 1);

/*INSERINDO SALARIO E CARGO EM FUNCIONARIOS, USANDO O UPDATE*/

UPDATE FUNCIONARIOS SET SALARIO = 1800.00 WHERE IDFUNCIONARIO = 1;
UPDATE FUNCIONARIOS SET CARGO = 'MECÂNICO' WHERE IDFUNCIONARIO = 1;
UPDATE FUNCIONARIOS SET SALARIO = 2200.00 WHERE IDFUNCIONARIO = 2;
UPDATE FUNCIONARIOS SET CARGO = 'PINTOR' WHERE IDFUNCIONARIO = 2;
UPDATE FUNCIONARIOS SET SALARIO = 2000.00 WHERE IDFUNCIONARIO = 3;
UPDATE FUNCIONARIOS SET CARGO = 'MECÂNICO' WHERE IDFUNCIONARIO = 3;
UPDATE FUNCIONARIOS SET SALARIO = 1900.00 WHERE IDFUNCIONARIO = 4;
UPDATE FUNCIONARIOS SET CARGO = 'PINTOR' WHERE IDFUNCIONARIO = 4;

/*INSERINDO AS MARCAS DOS CARROS*/

INSERT INTO MARCA VALUES(NULL, 'FIAT');
INSERT INTO MARCA VALUES(NULL, 'FORD');
INSERT INTO MARCA VALUES(NULL, 'CHEVROLET');
INSERT INTO MARCA VALUES(NULL, 'TOYOTA');
INSERT INTO MARCA VALUES(NULL, 'NISSAN');

/*INSERINDO OS DADOS DOS CARROS */

INSERT INTO CARROS VALUES(NULL,'ARGO','XIA-1137',1, 3); 
INSERT INTO CARROS VALUES(NULL,'COROLA','NNN-8711',4, 6); 
INSERT INTO CARROS VALUES(NULL,'FUSION','XXX-6666',2, 8); 
INSERT INTO CARROS VALUES(NULL,'MARCH','IYQ-7943',5, 1); 
INSERT INTO CARROS VALUES(NULL,'CRONOS','GTB-7780',1, 7); 
INSERT INTO CARROS VALUES(NULL,'HILUX','AFT-6973',4, 5); 
INSERT INTO CARROS VALUES(NULL,'KA','CUU-2424',2, 4); 
INSERT INTO CARROS VALUES(NULL,'ONIX','ROL-8006',3, 2); 

/* INSERINDO AS PINTURAS*/ 

INSERT INTO PINTURA VALUES(NULL,'AZUL','SOLIDA', 200.00); 
INSERT INTO PINTURA VALUES(NULL,'AZUL','PEROLADA', 250.00); 
INSERT INTO PINTURA VALUES(NULL,'AZUL','METALITA', 300.00); 
INSERT INTO PINTURA VALUES(NULL,'VERMELHO','SOLIDA', 350.00); 
INSERT INTO PINTURA VALUES(NULL,'VERMELHO','PEROLADA', 400.00); 
INSERT INTO PINTURA VALUES(NULL,'VERMELHO','METALITA', 450.00); 
INSERT INTO PINTURA VALUES(NULL,'PRETO','SOLIDA', 500.00);
INSERT INTO PINTURA VALUES(NULL,'PRETO','PEROLADA', 550.00);
INSERT INTO PINTURA VALUES(NULL,'PRETO','METALITA', 600.00);
INSERT INTO PINTURA VALUES(NULL,'PRATA','SOLIDA', 650.00);
INSERT INTO PINTURA VALUES(NULL,'PRATA','PEROLADA', 700.00);
INSERT INTO PINTURA VALUES(NULL,'PRATA','METALITA', 750.00);
INSERT INTO PINTURA VALUES(NULL,'BRANCO','SOLIDA', 800.00);
INSERT INTO PINTURA VALUES(NULL,'BRANCO','METALITA', 850.00);
INSERT INTO PINTURA VALUES(NULL,'BRANCO','PEROLADA', 900.00);

/*INSERINDO AS MANUTENÇÕES*/

INSERT INTO MANUTENÇÃO VALUES(NULL,'TROCA DE ÓLEO', 120.00);
INSERT INTO MANUTENÇÃO VALUES(NULL,'TROCA DE PNEU', 50.00);
INSERT INTO MANUTENÇÃO VALUES(NULL,'LIMPEZA DE MOTOR', 450.00);
INSERT INTO MANUTENÇÃO VALUES(NULL,'TROCA DE COMPONENTES', 200.00);
INSERT INTO MANUTENÇÃO VALUES(NULL,'TROCA DE FREIO', 750.00);
INSERT INTO MANUTENÇÃO VALUES(NULL,'REVISÃO COMPLETA', 1000.00);

/*INSERINDO OS SERVIÇOS*/

INSERT INTO SERVIÇOS VALUES(NULL,'250.00', 1 , 2, 1); 
INSERT INTO SERVIÇOS VALUES(NULL,'500.00', 3 , 4, 2); 
INSERT INTO SERVIÇOS VALUES(NULL,'1550.00', 8 , 6, 4); 
INSERT INTO SERVIÇOS VALUES(NULL,'1200.00', 6 , 5, 3); 
INSERT INTO SERVIÇOS VALUES(NULL,'970.00', 14 , 1, 1); 
INSERT INTO SERVIÇOS VALUES(NULL,'1100.00', 10 , 3, 4); 
INSERT INTO SERVIÇOS VALUES(NULL,'450.00', 5 , 2, 3); 
INSERT INTO SERVIÇOS VALUES(NULL,'1600.00', 9 , 6, 2); 

/*INSERINDO OS CONTRATOS QUE RELACIONAM CARRO E SERVIÇOS*/

INSERT INTO CONTRATO VALUES(1, 7);
INSERT INTO CONTRATO VALUES(2, 4);
INSERT INTO CONTRATO VALUES(3, 8);
INSERT INTO CONTRATO VALUES(4, 6);
INSERT INTO CONTRATO VALUES(5, 1);
INSERT INTO CONTRATO VALUES(6, 3);
INSERT INTO CONTRATO VALUES(7, 5);
INSERT INTO CONTRATO VALUES(8, 2);

/*----------------------------------------------------------------------------------------------------------------------------------------*/

/*SELECTS*/

SELECT *FROM ENDEREÇO;
SELECT *FROM PESSOA;
SELECT *FROM CLIENTES;
SELECT *FROM FUNCIONARIOS;
SELECT *FROM CARROS;
SELECT *FROM MARCA;
SELECT *FROM SERVIÇOS;
SELECT *FROM PINTURA;
SELECT *FROM MANUTENÇÃO;
SELECT *FROM CONTRATO;




/*-------------------------------------------------------------------------------------------------------------------------------------------*/

/* CRIANDO AS VIEWS*/

CREATE VIEW RELATORIO_CLIENTE_ENDEREÇO AS
SELECT 	P.IDPESSOA, C.IDCLIENTE, C.NOME, C.CPF, P.SEXO, C.TELEFONE, P.EMAIL, 
		E.IDENDEREÇO, E.RUA, E.BAIRRO, E.NUMERO, E.CEP
FROM PESSOA P 
INNER JOIN ENDEREÇO E 
ON P.IDENDEREÇO = E.IDENDEREÇO
INNER JOIN CLIENTES C 
ON C.IDPESSOA = P.IDPESSOA;

SELECT *FROM RELATORIO_CLIENTE_ENDEREÇO;

CREATE VIEW RELATORIO_CLIENTE_CARRO_MARCA AS
SELECT  C.IDCLIENTE, C.NOME, C.CPF, C.TELEFONE, 
		CR.IDCARRO, CR.PLACA, CR.MODELO, M.IDMARCA, M.MARCA   
FROM CLIENTES C
INNER JOIN CARROS CR 
ON C.IDCLIENTE = CR.IDCLIENTE
INNER JOIN MARCA M 
ON CR.IDMARCA = M.IDMARCA;

SELECT *FROM RELATORIO_CLIENTE_CARRO_MARCA;

CREATE VIEW RELATORIO_CARRO_MARCA_SERVIÇOS AS
SELECT CR.IDCARRO, CR.PLACA, CR.MODELO, M.IDMARCA, M.MARCA,
		CT.IDSERVIÇO,
		S.PREÇO_T
FROM CONTRATO CT 
INNER JOIN CARROS CR
ON CT.IDCARRO = CR.IDCARRO
INNER JOIN MARCA M
ON CR.IDMARCA = M.IDMARCA
INNER JOIN SERVIÇOS S 
ON S.IDSERVIÇO = CR.IDCARRO;

SELECT *FROM RELATORIO_CARRO_MARCA_SERVIÇOS;


CREATE VIEW RELATORIO_SERVIÇO_PINTURA_MANUTENÇÃO AS
SELECT S.IDSERVIÇO, S.PREÇO_T, P.IDPINTURA, P.COR, P.TIPO AS TIPO_PINTURA, P.PREÇO_P,
		MN.IDMANUTENÇÃO, MN.TIPO AS TIPO_MANUTENÇÃO, MN.PREÇO_M
        
FROM SERVIÇOS S 
INNER JOIN PINTURA P
ON S.IDPINTURA = P.IDPINTURA
INNER JOIN MANUTENÇÃO MN
ON S.IDMANUTENÇÃO = MN.IDMANUTENÇÃO;

SELECT *FROM RELATORIO_SERVIÇO_PINTURA_MANUTENÇÃO;


CREATE VIEW RELATORIO_SERVIÇO_CARRO_MARCA_FUNCIONARIO AS
SELECT CR.IDCARRO, CR.PLACA, CR.MODELO, M.IDMARCA, M.MARCA,
		CT.IDSERVIÇO,
		S.PREÇO_T, F.IDFUNCIONARIO, F.NOME, F.TELEFONE, F.CARGO, F.SALARIO
FROM CONTRATO CT 
INNER JOIN CARROS CR
ON CT.IDCARRO = CR.IDCARRO
INNER JOIN MARCA M
ON CR.IDMARCA = M.IDMARCA
INNER JOIN SERVIÇOS S 
ON S.IDSERVIÇO = CR.IDCARRO
INNER JOIN FUNCIONARIOS F 
ON S.IDFUNCIONARIO = F.IDFUNCIONARIO;

SELECT *FROM RELATORIO_SERVIÇO_CARRO_MARCA_FUNCIONARIO;


CREATE VIEW RELATORIO_CLIENTE_CARRO_MARCA_SERVIÇO_FUNCIONARIO AS
SELECT  C.IDCLIENTE, C.NOME AS CLIENTE, C.TELEFONE, 
		CR.IDCARRO, CR.PLACA, CR.MODELO, M.IDMARCA, M.MARCA,
        S.IDSERVIÇO, S.PREÇO_T AS PREÇO_TOTAL, P.COR, P.TIPO AS TIPO_PINTURA, P.PREÇO_P,
        MN.TIPO AS TIPO_MANUTENÇÃO, MN.PREÇO_M,
        F.NOME AS FUNCIONARIO, F.CARGO, F.SALARIO
FROM CONTRATO CT 
INNER JOIN CARROS CR
ON CT.IDCARRO = CR.IDCARRO
INNER JOIN SERVIÇOS S
ON S.IDSERVIÇO = CT.IDSERVIÇO
INNER JOIN CLIENTES C
ON C.IDCLIENTE = CR.IDCLIENTE
INNER JOIN MARCA M 
ON CR.IDMARCA = M.IDMARCA
INNER JOIN PINTURA P 
ON S.IDPINTURA = P.IDPINTURA
INNER JOIN MANUTENÇÃO MN 
ON S.IDMANUTENÇÃO = MN.IDMANUTENÇÃO
INNER JOIN FUNCIONARIOS F
ON S.IDFUNCIONARIO = F.IDFUNCIONARIO;

SELECT *FROM RELATORIO_CLIENTE_CARRO_MARCA_SERVIÇO_FUNCIONARIO;


/*PREÇO MEDIO DE PINTURA E MANUTENÇÃO*/

CREATE VIEW RELATORIO_PREÇO_MEDIO AS
SELECT AVG(PREÇO_P) AS PREÇO_MEDIO_PINTURA, AVG(PREÇO_M) AS PREÇO_MEDIO_MANUTENÇÃO
FROM SERVIÇOS S 
INNER JOIN PINTURA P 
ON P.IDPINTURA = S.IDPINTURA
INNER JOIN MANUTENÇÃO M
ON M.IDMANUTENÇÃO = S.IDMANUTENÇÃO;

SELECT * FROM RELATORIO_PREÇO_MEDIO;

/*GASTOS*/
CREATE VIEW RELATORIO_GASTOS AS
SELECT SUM(S.PREÇO_T) AS PREÇO_DE_TODOS_SERVIÇOS,
	SUM(F.SALARIO) AS GASTO_COM_FUNCIONARIO
FROM SERVIÇOS S
INNER JOIN FUNCIONARIOS F
ON S.IDFUNCIONARIO = F.IDFUNCIONARIO;

SELECT * FROM RELATORIO_GASTOS;

